import { CouleurType } from "./couleurType";
import { ReservationStatusType } from "./reservationStatusType";
import { TypeVehiculeType } from "./typeVehiculeType";
import { VoyageAvecType } from "./voyageAvecType";

export class RechTrajetAnnonceDto {
  id: bigint;
  depart: string;
  destination: string;
  dateHeureDepart: Date;
  prix: bigint;
  nombrePlaces: bigint;
  nombrePlacesDispo: bigint;
  voyageAvec: VoyageAvecType;
  instantane: boolean;
  vMarque: string;
  vModele: string;
  vClimatise: boolean;
  vCouleur: CouleurType;
  vTypeVehicule: TypeVehiculeType;
  vVerifie: boolean;
  vImage1: string;
  vImage1Href: string;
  cigarette: boolean;
  animaux: boolean;
  max2: boolean;
  leger: boolean;
  moyen: boolean;
  lourd: boolean;
  userId: bigint;
  uImgUrl: string;
  uId: string;
  uNom: string;
  uPrenom: string;
  uSexe: string;
  uSuperDriver: boolean;
  uSuperUser: boolean;
  uVerifie: boolean;
  isRes: boolean;
  statutRes: ReservationStatusType;
}
